apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biblio-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: biblio-app 
    repoURL: "https://github.com/nadineziadi/argocdbiblioApp.git" 
    targetRevision: HEAD 
  syncPolicy:
    automated: {} 
  syncOptions:
    - CreateNamespace=true
